apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: source
  name: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  strategy: {}
  template:
    metadata:
      labels:
        app: source
    spec:
      containers:
      - image: httpd
        name: httpd
