apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: target
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: target
  targetCPUUtilizationPercentage: 30
